service: sagemaker-invoker
 
frameworkVersion: ">=1.34.0 < 2.0.0" 
 
provider: 
  name: aws 
  profile: 'sagemaker-invoker'
  runtime: python3.6
  stage: ${opt:stage, 'dev'} 
  region: us-east-2

custom: 
  pythonRequirements:
    dockerizePip: non-linux
  stage: ${opt:stage, self:provider.stage} 
  region: ${opt:region, self:provider.region} 
    
package: 
  exclude: 
    - node_modules/**
    
functions:
  SagemakerInvoker:
    handler: src/sagemaker-invoker.lambda_handler
    description: Invoke Sagemaker Endpoint
    memorySize: 128
    timeout: 30
    events:
        - http: POST lambda_handler
    environment:
        ENDPOINT_NAME: 'sagemaker-scikit-learn-2020-01-21-20-47-28-587'  # TODO auto update
    package: 
      include: 
        - src/sagemaker-invoker
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sagemaker:InvokeEndpoint
        Resource: '*'

resources:
  Resources:

plugins:
  - serverless-python-requirements
  - serverless-iam-roles-per-function